jdk:
  - oraclejdk7
before_install:
  - wget dist.neo4j.org/neo4j-community-2.1.8-unix.tar.gz
  - tar -zxf neo4j-community-2.1.8-unix.tar.gz
  - neo4j-community-2.1.8/bin/neo4j start

language: node_js
node_js:
  - "4.1.1"

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: XlBuTWq58C1WJ6inFX4iegbX4Udc5A1Mun/QqqSnD328KxCfRVGmPD4GMo/DMIyoHc9Z4F2NypVl5LIMmM0pgBjHavQiHXfJhHE8lo9UsKP7xpvP1XZD4Sdfn+yJRXjgBWpsQR6JV8l66MdHrGpdB9AcyFbNthJxdl9CyGAXEeo=
  app:
    master: techdb-api
    dev: techdb-api-staging
